markdown:            kramdown
highlighter:         rouge
include:             ['_pages', '_subpages']

# Permalinks
permalink:           pretty

# Setup
title:               Daniel Libatique
tagline:             'Classics Teacher and Researcher'
url:                 https://libatique.info
baseurl:             /

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Daniel Libatique
  url:               https://libatique.info

# Custom vars
version:             2.1.0
github:
  repo:              https://github.com/dlibatique/dlibatique.github.io
